name: Nightly builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Set Secret Properties
      env: 
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: echo "$LOCAL_PROPERTIES" > ./local.properties
    
    - name: Prepare release keystore
      run: |
        echo "${{ secrets.BASE_64_SIGNING_KEY }}" > release_keystore.jks.asc
        gpg -d --passphrase "${{ secrets.BASE_64_SIGNING_KEY_PASSPHRASE }}" --batch release_keystore.jks.asc > release_keystore.jks
    
    - name: Build with Gradle
      run: ./gradlew assembleNightly
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
       name: moshidon-nightly
       path: ./mastodon/build/outputs/apk/nightly/moshidon-nightly.apk
